FROM ubuntu:latest

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update

RUN apt-get -y install mc 
RUN apt-get -y install vim  
RUN apt-get -y install libconfig++

ENV WORKSPACE=/root/repo

WORKDIR /root

