# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobile_messages.proto',
  package='mobile_messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15mobile_messages.proto\x12\x0fmobile_messages\"#\n\x0eNetworkMessage\x12\x11\n\tmessageId\x18\x01 \x02(\x05\"%\n\x10HandshakeRequest\x12\x11\n\tmessageId\x18\x01 \x02(\x05\"Y\n\x11HandshakeResponse\x12\x11\n\tmessageId\x18\x01 \x02(\x05\x12\x10\n\x08mobileId\x18\x02 \x02(\x05\"\x1f\n\x0cResponseType\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03NOK\x10\x01')
)



_HANDSHAKERESPONSE_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='mobile_messages.HandshakeResponse.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOK', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=176,
  serialized_end=207,
)
_sym_db.RegisterEnumDescriptor(_HANDSHAKERESPONSE_RESPONSETYPE)


_NETWORKMESSAGE = _descriptor.Descriptor(
  name='NetworkMessage',
  full_name='mobile_messages.NetworkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageId', full_name='mobile_messages.NetworkMessage.messageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=77,
)


_HANDSHAKEREQUEST = _descriptor.Descriptor(
  name='HandshakeRequest',
  full_name='mobile_messages.HandshakeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageId', full_name='mobile_messages.HandshakeRequest.messageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=116,
)


_HANDSHAKERESPONSE = _descriptor.Descriptor(
  name='HandshakeResponse',
  full_name='mobile_messages.HandshakeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageId', full_name='mobile_messages.HandshakeResponse.messageId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobileId', full_name='mobile_messages.HandshakeResponse.mobileId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HANDSHAKERESPONSE_RESPONSETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=207,
)

_HANDSHAKERESPONSE_RESPONSETYPE.containing_type = _HANDSHAKERESPONSE
DESCRIPTOR.message_types_by_name['NetworkMessage'] = _NETWORKMESSAGE
DESCRIPTOR.message_types_by_name['HandshakeRequest'] = _HANDSHAKEREQUEST
DESCRIPTOR.message_types_by_name['HandshakeResponse'] = _HANDSHAKERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkMessage = _reflection.GeneratedProtocolMessageType('NetworkMessage', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKMESSAGE,
  __module__ = 'mobile_messages_pb2'
  # @@protoc_insertion_point(class_scope:mobile_messages.NetworkMessage)
  ))
_sym_db.RegisterMessage(NetworkMessage)

HandshakeRequest = _reflection.GeneratedProtocolMessageType('HandshakeRequest', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKEREQUEST,
  __module__ = 'mobile_messages_pb2'
  # @@protoc_insertion_point(class_scope:mobile_messages.HandshakeRequest)
  ))
_sym_db.RegisterMessage(HandshakeRequest)

HandshakeResponse = _reflection.GeneratedProtocolMessageType('HandshakeResponse', (_message.Message,), dict(
  DESCRIPTOR = _HANDSHAKERESPONSE,
  __module__ = 'mobile_messages_pb2'
  # @@protoc_insertion_point(class_scope:mobile_messages.HandshakeResponse)
  ))
_sym_db.RegisterMessage(HandshakeResponse)


# @@protoc_insertion_point(module_scope)
