// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile_messages.proto

#include "mobile_messages.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace mobile_messages {
class NetworkMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NetworkMessage>
      _instance;
} _NetworkMessage_default_instance_;
class HandshakeRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HandshakeRequest>
      _instance;
} _HandshakeRequest_default_instance_;
class HandshakeResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HandshakeResponse>
      _instance;
} _HandshakeResponse_default_instance_;
}  // namespace mobile_messages
namespace protobuf_mobile_5fmessages_2eproto {
static void InitDefaultsNetworkMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile_messages::_NetworkMessage_default_instance_;
    new (ptr) ::mobile_messages::NetworkMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile_messages::NetworkMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NetworkMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNetworkMessage}, {}};

static void InitDefaultsHandshakeRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile_messages::_HandshakeRequest_default_instance_;
    new (ptr) ::mobile_messages::HandshakeRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile_messages::HandshakeRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_HandshakeRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsHandshakeRequest}, {}};

static void InitDefaultsHandshakeResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile_messages::_HandshakeResponse_default_instance_;
    new (ptr) ::mobile_messages::HandshakeResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile_messages::HandshakeResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_HandshakeResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsHandshakeResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NetworkMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_HandshakeRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_HandshakeResponse.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::NetworkMessage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::NetworkMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::NetworkMessage, messageid_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeRequest, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeRequest, messageid_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeResponse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeResponse, messageid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile_messages::HandshakeResponse, mobileid_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::mobile_messages::NetworkMessage)},
  { 7, 13, sizeof(::mobile_messages::HandshakeRequest)},
  { 14, 21, sizeof(::mobile_messages::HandshakeResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile_messages::_NetworkMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile_messages::_HandshakeRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile_messages::_HandshakeResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "mobile_messages.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025mobile_messages.proto\022\017mobile_messages"
      "\"#\n\016NetworkMessage\022\021\n\tmessageId\030\001 \002(\005\"%\n"
      "\020HandshakeRequest\022\021\n\tmessageId\030\001 \002(\005\"Y\n\021"
      "HandshakeResponse\022\021\n\tmessageId\030\001 \002(\005\022\020\n\010"
      "mobileId\030\002 \002(\005\"\037\n\014ResponseType\022\006\n\002OK\020\000\022\007"
      "\n\003NOK\020\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 207);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mobile_messages.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mobile_5fmessages_2eproto
namespace mobile_messages {
const ::google::protobuf::EnumDescriptor* HandshakeResponse_ResponseType_descriptor() {
  protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mobile_5fmessages_2eproto::file_level_enum_descriptors[0];
}
bool HandshakeResponse_ResponseType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const HandshakeResponse_ResponseType HandshakeResponse::OK;
const HandshakeResponse_ResponseType HandshakeResponse::NOK;
const HandshakeResponse_ResponseType HandshakeResponse::ResponseType_MIN;
const HandshakeResponse_ResponseType HandshakeResponse::ResponseType_MAX;
const int HandshakeResponse::ResponseType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void NetworkMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NetworkMessage::kMessageIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NetworkMessage::NetworkMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_5fmessages_2eproto::scc_info_NetworkMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile_messages.NetworkMessage)
}
NetworkMessage::NetworkMessage(const NetworkMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  messageid_ = from.messageid_;
  // @@protoc_insertion_point(copy_constructor:mobile_messages.NetworkMessage)
}

void NetworkMessage::SharedCtor() {
  messageid_ = 0;
}

NetworkMessage::~NetworkMessage() {
  // @@protoc_insertion_point(destructor:mobile_messages.NetworkMessage)
  SharedDtor();
}

void NetworkMessage::SharedDtor() {
}

void NetworkMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NetworkMessage::descriptor() {
  ::protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NetworkMessage& NetworkMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_5fmessages_2eproto::scc_info_NetworkMessage.base);
  return *internal_default_instance();
}


void NetworkMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile_messages.NetworkMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messageid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool NetworkMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile_messages.NetworkMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 messageId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_messageid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messageid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mobile_messages.NetworkMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile_messages.NetworkMessage)
  return false;
#undef DO_
}

void NetworkMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile_messages.NetworkMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messageid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile_messages.NetworkMessage)
}

::google::protobuf::uint8* NetworkMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile_messages.NetworkMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messageid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile_messages.NetworkMessage)
  return target;
}

size_t NetworkMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile_messages.NetworkMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 messageId = 1;
  if (has_messageid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messageid());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NetworkMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile_messages.NetworkMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const NetworkMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NetworkMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile_messages.NetworkMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile_messages.NetworkMessage)
    MergeFrom(*source);
  }
}

void NetworkMessage::MergeFrom(const NetworkMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile_messages.NetworkMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_messageid()) {
    set_messageid(from.messageid());
  }
}

void NetworkMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile_messages.NetworkMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NetworkMessage::CopyFrom(const NetworkMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile_messages.NetworkMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NetworkMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void NetworkMessage::Swap(NetworkMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NetworkMessage::InternalSwap(NetworkMessage* other) {
  using std::swap;
  swap(messageid_, other->messageid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NetworkMessage::GetMetadata() const {
  protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void HandshakeRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HandshakeRequest::kMessageIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HandshakeRequest::HandshakeRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_5fmessages_2eproto::scc_info_HandshakeRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile_messages.HandshakeRequest)
}
HandshakeRequest::HandshakeRequest(const HandshakeRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  messageid_ = from.messageid_;
  // @@protoc_insertion_point(copy_constructor:mobile_messages.HandshakeRequest)
}

void HandshakeRequest::SharedCtor() {
  messageid_ = 0;
}

HandshakeRequest::~HandshakeRequest() {
  // @@protoc_insertion_point(destructor:mobile_messages.HandshakeRequest)
  SharedDtor();
}

void HandshakeRequest::SharedDtor() {
}

void HandshakeRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* HandshakeRequest::descriptor() {
  ::protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HandshakeRequest& HandshakeRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_5fmessages_2eproto::scc_info_HandshakeRequest.base);
  return *internal_default_instance();
}


void HandshakeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile_messages.HandshakeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messageid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool HandshakeRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile_messages.HandshakeRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 messageId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_messageid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messageid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mobile_messages.HandshakeRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile_messages.HandshakeRequest)
  return false;
#undef DO_
}

void HandshakeRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile_messages.HandshakeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messageid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile_messages.HandshakeRequest)
}

::google::protobuf::uint8* HandshakeRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile_messages.HandshakeRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messageid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile_messages.HandshakeRequest)
  return target;
}

size_t HandshakeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile_messages.HandshakeRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 messageId = 1;
  if (has_messageid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messageid());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HandshakeRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile_messages.HandshakeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const HandshakeRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HandshakeRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile_messages.HandshakeRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile_messages.HandshakeRequest)
    MergeFrom(*source);
  }
}

void HandshakeRequest::MergeFrom(const HandshakeRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile_messages.HandshakeRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_messageid()) {
    set_messageid(from.messageid());
  }
}

void HandshakeRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile_messages.HandshakeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HandshakeRequest::CopyFrom(const HandshakeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile_messages.HandshakeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HandshakeRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void HandshakeRequest::Swap(HandshakeRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HandshakeRequest::InternalSwap(HandshakeRequest* other) {
  using std::swap;
  swap(messageid_, other->messageid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata HandshakeRequest::GetMetadata() const {
  protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void HandshakeResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HandshakeResponse::kMessageIdFieldNumber;
const int HandshakeResponse::kMobileIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HandshakeResponse::HandshakeResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_5fmessages_2eproto::scc_info_HandshakeResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile_messages.HandshakeResponse)
}
HandshakeResponse::HandshakeResponse(const HandshakeResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&messageid_, &from.messageid_,
    static_cast<size_t>(reinterpret_cast<char*>(&mobileid_) -
    reinterpret_cast<char*>(&messageid_)) + sizeof(mobileid_));
  // @@protoc_insertion_point(copy_constructor:mobile_messages.HandshakeResponse)
}

void HandshakeResponse::SharedCtor() {
  ::memset(&messageid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mobileid_) -
      reinterpret_cast<char*>(&messageid_)) + sizeof(mobileid_));
}

HandshakeResponse::~HandshakeResponse() {
  // @@protoc_insertion_point(destructor:mobile_messages.HandshakeResponse)
  SharedDtor();
}

void HandshakeResponse::SharedDtor() {
}

void HandshakeResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* HandshakeResponse::descriptor() {
  ::protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HandshakeResponse& HandshakeResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_5fmessages_2eproto::scc_info_HandshakeResponse.base);
  return *internal_default_instance();
}


void HandshakeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile_messages.HandshakeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&messageid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&mobileid_) -
        reinterpret_cast<char*>(&messageid_)) + sizeof(mobileid_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool HandshakeResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile_messages.HandshakeResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 messageId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_messageid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messageid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 mobileId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_mobileid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mobileid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mobile_messages.HandshakeResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile_messages.HandshakeResponse)
  return false;
#undef DO_
}

void HandshakeResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile_messages.HandshakeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messageid(), output);
  }

  // required int32 mobileId = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mobileid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile_messages.HandshakeResponse)
}

::google::protobuf::uint8* HandshakeResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile_messages.HandshakeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 messageId = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messageid(), target);
  }

  // required int32 mobileId = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mobileid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile_messages.HandshakeResponse)
  return target;
}

size_t HandshakeResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:mobile_messages.HandshakeResponse)
  size_t total_size = 0;

  if (has_messageid()) {
    // required int32 messageId = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messageid());
  }

  if (has_mobileid()) {
    // required int32 mobileId = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mobileid());
  }

  return total_size;
}
size_t HandshakeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile_messages.HandshakeResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 messageId = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messageid());

    // required int32 mobileId = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mobileid());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HandshakeResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile_messages.HandshakeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const HandshakeResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HandshakeResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile_messages.HandshakeResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile_messages.HandshakeResponse)
    MergeFrom(*source);
  }
}

void HandshakeResponse::MergeFrom(const HandshakeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile_messages.HandshakeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      messageid_ = from.messageid_;
    }
    if (cached_has_bits & 0x00000002u) {
      mobileid_ = from.mobileid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void HandshakeResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile_messages.HandshakeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HandshakeResponse::CopyFrom(const HandshakeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile_messages.HandshakeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HandshakeResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void HandshakeResponse::Swap(HandshakeResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HandshakeResponse::InternalSwap(HandshakeResponse* other) {
  using std::swap;
  swap(messageid_, other->messageid_);
  swap(mobileid_, other->mobileid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata HandshakeResponse::GetMetadata() const {
  protobuf_mobile_5fmessages_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_5fmessages_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mobile_messages
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile_messages::NetworkMessage* Arena::CreateMaybeMessage< ::mobile_messages::NetworkMessage >(Arena* arena) {
  return Arena::CreateInternal< ::mobile_messages::NetworkMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile_messages::HandshakeRequest* Arena::CreateMaybeMessage< ::mobile_messages::HandshakeRequest >(Arena* arena) {
  return Arena::CreateInternal< ::mobile_messages::HandshakeRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile_messages::HandshakeResponse* Arena::CreateMaybeMessage< ::mobile_messages::HandshakeResponse >(Arena* arena) {
  return Arena::CreateInternal< ::mobile_messages::HandshakeResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
